### ISSUE TITLE
What exactly is "tx"

### ISSUE THREAD

**Issue by Head** [mappum/bitcoin-inventory#1]
> `inv.broadcast(tx)`
> 
> Adds `tx` to the inventory

I'm using bitcoinjs to generate a transaction:

```
var tx = new bitcoinjs.TransactionBuilder();
...
tx.addOutput(addr, 1000);
tx.sign(0, keyPair);
inv.broadcast(tx.build());
```

But then I'll get "Transaction output values must be a BN.js number or a Buffer".

But bitcoinjs can't work with BN or Buffers. They need a UInt53.

I've seen there is some transform stuff in bitcoin-net. But I don't know how to use it.

**Comment by mappum** [comment]
You're right, this should support UInt53 output amounts. I just published `bitcoin-net@5.3.0` which now supports this, so bitcoinjs transactions should work out of the box.

BTW, the protocol transform stuff is just for internal use, you shouldn't need to access it.
